[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mining_room = "61zXhvyP5jZhnj2X8XjT6S6Q1HJZk1wt4MPf9vVg89fq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/mining_room"]

[test]
startup_wait = 8000
shutdown_wait = 2000
upgradeable = false
