[workspace]
resolver = "2"
members = [
    "programs/mining_room",
]

[workspace.dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
solana-program = "1.18.15"

[profile.release]
overflow-checks = true

